-- Security and workflow hardening. Additive and backwards compatible.

alter table public.anmeldungen
  add column if not exists erstattet_am timestamptz,
  add column if not exists stripe_refund_id text,
  add column if not exists refund_reason text;

create table if not exists public.confirmation_tokens (
  token_hash text primary key,
  subject_type text not null check (subject_type in ('registration', 'company_registration')),
  subject_id uuid not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  constraint confirmation_tokens_hash_format check (token_hash ~ '^[a-f0-9]{64}$')
);
create index if not exists confirmation_tokens_subject_idx
  on public.confirmation_tokens (subject_type, subject_id, created_at desc);
create index if not exists confirmation_tokens_expiry_idx
  on public.confirmation_tokens (expires_at) where revoked_at is null;

create table if not exists public.form_submission_nonces (
  nonce_hash text primary key,
  purpose text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz not null default now(),
  constraint form_submission_nonces_hash_format check (nonce_hash ~ '^[a-f0-9]{64}$')
);

create table if not exists public.form_rate_limits (
  scope text not null,
  identity_hash text not null,
  window_started_at timestamptz not null default now(),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  blocked_until timestamptz,
  updated_at timestamptz not null default now(),
  primary key (scope, identity_hash),
  constraint form_rate_limits_hash_format check (identity_hash ~ '^[a-f0-9]{64}$')
);
create index if not exists form_rate_limits_updated_idx on public.form_rate_limits (updated_at);

create table if not exists public.email_campaign_runs (
  id uuid primary key default gen_random_uuid(),
  campaign_type text not null,
  camp_id uuid references public.camps(id) on delete restrict,
  requested_by text,
  status text not null default 'running' check (status in ('running', 'completed', 'partial', 'failed')),
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  error_summary text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create unique index if not exists email_campaign_once_idx
  on public.email_campaign_runs (campaign_type, camp_id)
  where status in ('running', 'completed', 'partial');

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  payment_intent_id text,
  registration_id uuid references public.anmeldungen(id) on delete set null,
  amount_cents integer,
  currency text,
  status text not null default 'received' check (status in ('received', 'processed', 'ignored', 'rejected', 'failed')),
  message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);
create unique index if not exists stripe_payment_intent_registration_unique_idx
  on public.stripe_webhook_events (payment_intent_id)
  where payment_intent_id is not null and status = 'processed';

create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  actor_user_id uuid,
  actor_email text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists security_audit_record_idx
  on public.security_audit_log (table_name, record_id, created_at desc);

create table if not exists public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  message_type text not null,
  recipient text not null,
  payload jsonb not null,
  status text not null default 'pending' check (status in ('pending', 'sending', 'sent', 'failed')),
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
create index if not exists email_outbox_pending_idx
  on public.email_outbox (next_attempt_at, created_at) where status in ('pending', 'failed');

alter table public.confirmation_tokens enable row level security;
alter table public.form_submission_nonces enable row level security;
alter table public.form_rate_limits enable row level security;
alter table public.email_campaign_runs enable row level security;
alter table public.stripe_webhook_events enable row level security;
alter table public.security_audit_log enable row level security;
alter table public.email_outbox enable row level security;

revoke all on table public.confirmation_tokens, public.form_submission_nonces,
  public.form_rate_limits, public.email_campaign_runs, public.stripe_webhook_events,
  public.security_audit_log, public.email_outbox from public, anon, authenticated;
grant all on table public.confirmation_tokens, public.form_submission_nonces,
  public.form_rate_limits, public.email_campaign_runs, public.stripe_webhook_events,
  public.security_audit_log, public.email_outbox to service_role;
grant usage, select on sequence public.security_audit_log_id_seq to service_role;

create or replace function public.consume_form_nonce(
  p_nonce_hash text,
  p_purpose text,
  p_expires_at timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  inserted_count integer;
begin
  if p_nonce_hash !~ '^[a-f0-9]{64}$' or btrim(p_purpose) = ''
    or p_expires_at <= now() or p_expires_at > now() + interval '3 hours' then
    return false;
  end if;
  delete from public.form_submission_nonces where expires_at < now() - interval '1 day';
  insert into public.form_submission_nonces (nonce_hash, purpose, expires_at)
  values (p_nonce_hash, p_purpose, p_expires_at)
  on conflict do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace function public.consume_form_rate_limit(
  p_scope text,
  p_identity_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  state public.form_rate_limits%rowtype;
  window_interval interval;
begin
  if btrim(p_scope) = '' or p_identity_hash !~ '^[a-f0-9]{64}$'
    or p_limit < 1 or p_window_seconds < 10 or p_window_seconds > 86400 then
    return false;
  end if;
  window_interval := make_interval(secs => p_window_seconds);
  delete from public.form_rate_limits where updated_at < now() - interval '7 days';
  insert into public.form_rate_limits (scope, identity_hash)
  values (p_scope, p_identity_hash) on conflict do nothing;
  select * into state from public.form_rate_limits
    where scope = p_scope and identity_hash = p_identity_hash for update;
  if state.blocked_until is not null and state.blocked_until > now() then
    return false;
  end if;
  if state.window_started_at <= now() - window_interval then
    state.window_started_at := now();
    state.attempt_count := 0;
  end if;
  state.attempt_count := state.attempt_count + 1;
  update public.form_rate_limits set
    window_started_at = state.window_started_at,
    attempt_count = state.attempt_count,
    blocked_until = case when state.attempt_count > p_limit then now() + window_interval else null end,
    updated_at = now()
  where scope = p_scope and identity_hash = p_identity_hash;
  return state.attempt_count <= p_limit;
end;
$$;

revoke all on function public.consume_form_nonce(text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.consume_form_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_form_nonce(text, text, timestamptz) to service_role;
grant execute on function public.consume_form_rate_limit(text, text, integer, integer) to service_role;

create or replace function public.audit_sensitive_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  claims jsonb := coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb;
  old_row jsonb := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_row jsonb := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
begin
  insert into public.security_audit_log (
    table_name, record_id, action, actor_user_id, actor_email, old_data, new_data
  ) values (
    tg_table_name,
    coalesce(new_row ->> 'id', old_row ->> 'id'),
    tg_op,
    nullif(claims ->> 'sub', '')::uuid,
    lower(nullif(claims ->> 'email', '')),
    old_row,
    new_row
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists audit_anmeldungen_changes on public.anmeldungen;
create trigger audit_anmeldungen_changes after insert or update or delete on public.anmeldungen
  for each row execute function public.audit_sensitive_change();
drop trigger if exists audit_firmen_anmeldungen_changes on public.firmen_anmeldungen;
create trigger audit_firmen_anmeldungen_changes after insert or update or delete on public.firmen_anmeldungen
  for each row execute function public.audit_sensitive_change();
drop trigger if exists audit_camps_changes on public.camps;
create trigger audit_camps_changes after insert or update or delete on public.camps
  for each row execute function public.audit_sensitive_change();
drop trigger if exists audit_teilnahme_changes on public.teilnahme;
create trigger audit_teilnahme_changes after insert or update or delete on public.teilnahme
  for each row execute function public.audit_sensitive_change();

create or replace function public.guard_anmeldung_booking()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  camp_row record;
  occupied integer;
begin
  if tg_op = 'UPDATE' and new.camp_id = old.camp_id
    and coalesce(old.zahlungsstatus, 'offen') not in ('storniert', 'erstattet') then
    return new;
  end if;
  if coalesce(new.zahlungsstatus, 'offen') in ('storniert', 'erstattet') then return new; end if;
  perform pg_advisory_xact_lock(hashtextextended(new.camp_id::text, 0));
  select id, status, max_plaetze, datum_bis into camp_row
    from public.camps where id = new.camp_id for update;
  if not found or camp_row.status <> 'aktiv' or camp_row.datum_bis < current_date then
    raise exception using errcode = 'P0001', message = 'CAMP_NOT_BOOKABLE';
  end if;
  if exists (
    select 1 from public.anmeldungen a where a.camp_id = new.camp_id
      and lower(a.vorname) = lower(new.vorname) and lower(a.nachname) = lower(new.nachname)
      and lower(a.email) = lower(new.email)
      and coalesce(a.zahlungsstatus, 'offen') not in ('storniert', 'erstattet')
      and (tg_op <> 'UPDATE' or a.id <> new.id)
  ) then raise exception using errcode = '23505', message = 'REGISTRATION_DUPLICATE'; end if;
  select
    (select count(*) from public.anmeldungen a where a.camp_id = new.camp_id
      and coalesce(a.payer_type, 'parent') <> 'company'
      and coalesce(a.zahlungsstatus, 'offen') not in ('storniert', 'erstattet')
      and (tg_op <> 'UPDATE' or a.id <> new.id))
    +
    (select count(*) from public.firmen_anmeldungen f where f.camp_id = new.camp_id
      and coalesce(f.status, 'bezahlt') not in ('storniert', 'erstattet'))
  into occupied;
  if occupied >= camp_row.max_plaetze then
    raise exception using errcode = 'P0001', message = 'CAMP_FULL';
  end if;
  return new;
end;
$$;

create or replace function public.guard_company_booking()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  camp_row record;
  occupied integer;
begin
  if tg_op = 'UPDATE' and new.camp_id = old.camp_id
    and coalesce(old.status, 'bezahlt') not in ('storniert', 'erstattet') then return new; end if;
  if coalesce(new.status, 'bezahlt') in ('storniert', 'erstattet') then return new; end if;
  perform pg_advisory_xact_lock(hashtextextended(new.camp_id::text, 0));
  select id, status, max_plaetze, datum_bis into camp_row
    from public.camps where id = new.camp_id for update;
  if not found or camp_row.status <> 'aktiv' or camp_row.datum_bis < current_date then
    raise exception using errcode = 'P0001', message = 'CAMP_NOT_BOOKABLE';
  end if;
  if exists (
    select 1 from public.firmen_anmeldungen f where f.camp_id = new.camp_id
      and lower(f.kind_vorname) = lower(new.kind_vorname)
      and lower(f.kind_nachname) = lower(new.kind_nachname)
      and coalesce(lower(f.mitarbeiter_email), '') = coalesce(lower(new.mitarbeiter_email), '')
      and coalesce(f.status, 'bezahlt') not in ('storniert', 'erstattet')
      and (tg_op <> 'UPDATE' or f.id <> new.id)
  ) then raise exception using errcode = '23505', message = 'REGISTRATION_DUPLICATE'; end if;
  select
    (select count(*) from public.anmeldungen a where a.camp_id = new.camp_id
      and coalesce(a.payer_type, 'parent') <> 'company'
      and coalesce(a.zahlungsstatus, 'offen') not in ('storniert', 'erstattet'))
    +
    (select count(*) from public.firmen_anmeldungen f where f.camp_id = new.camp_id
      and coalesce(f.status, 'bezahlt') not in ('storniert', 'erstattet')
      and (tg_op <> 'UPDATE' or f.id <> new.id))
  into occupied;
  if occupied >= camp_row.max_plaetze then
    raise exception using errcode = 'P0001', message = 'CAMP_FULL';
  end if;
  return new;
end;
$$;

drop trigger if exists guard_anmeldung_booking_trigger on public.anmeldungen;
create trigger guard_anmeldung_booking_trigger
  before insert or update of camp_id, zahlungsstatus, vorname, nachname, email on public.anmeldungen
  for each row execute function public.guard_anmeldung_booking();
drop trigger if exists guard_company_booking_trigger on public.firmen_anmeldungen;
create trigger guard_company_booking_trigger
  before insert or update of camp_id, status, kind_vorname, kind_nachname,
    mitarbeiter_email, mitarbeiter_telefon on public.firmen_anmeldungen
  for each row execute function public.guard_company_booking();

-- Public clients use the deliberately reduced availability view only.
revoke select, insert, update, delete on table public.camps, public.teilnahme from anon, public;
grant select on table public.camp_verfuegbarkeit_public to anon, authenticated;

comment on table public.confirmation_tokens is 'Widerrufbare, gehashte Bearer-Tokens für Bestätigungsabrufe.';
comment on table public.stripe_webhook_events is 'Idempotenz- und Zuordnungsjournal für Stripe Webhooks; keine Roh-Payloads.';
comment on table public.security_audit_log is 'Privates Änderungsjournal für sensible Dashboard- und Service-Operationen.';

create or replace function public.dashboard_delete_registration(
  p_table text,
  p_registration_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  deleted_count integer;
begin
  if not public.is_dashboard_admin() then
    raise exception using errcode = '42501', message = 'DASHBOARD_ADMIN_REQUIRED';
  end if;
  if p_table not in ('anmeldungen', 'firmen_anmeldungen') then
    raise exception using errcode = '22023', message = 'REGISTRATION_TABLE_INVALID';
  end if;
  delete from public.teilnahme where referenz_id = p_registration_id;
  if p_table = 'anmeldungen' then
    delete from public.anmeldungen where id = p_registration_id;
  else
    delete from public.firmen_anmeldungen where id = p_registration_id;
  end if;
  get diagnostics deleted_count = row_count;
  return deleted_count = 1;
end;
$$;
revoke all on function public.dashboard_delete_registration(text, uuid) from public, anon;
grant execute on function public.dashboard_delete_registration(text, uuid) to authenticated, service_role;
